-- Migration 000: Base schema required by the application.
-- Safe for existing databases: every object is created only if it is missing.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS tasks (
  id                  BIGINT PRIMARY KEY,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at_colombia TEXT,
  indicator           TEXT DEFAULT '',
  indicators          JSONB DEFAULT '[]'::jsonb,
  title               TEXT NOT NULL DEFAULT '',
  start_date          TEXT DEFAULT '',
  end_date            TEXT DEFAULT '',
  estimated_time      NUMERIC DEFAULT 5,
  type                TEXT DEFAULT 'Operativa',
  status              TEXT DEFAULT 'Sin iniciar',
  validation_close    TEXT,
  ext_progress1       TEXT DEFAULT '',
  ext_progress2       TEXT DEFAULT '',
  difficulty          NUMERIC DEFAULT 5,
  strategic_value     NUMERIC DEFAULT 5,
  expected_delivery   TEXT DEFAULT '',
  responsible         TEXT DEFAULT '',
  comments            TEXT DEFAULT '',
  progress_percent    NUMERIC DEFAULT 0,
  subtasks            JSONB DEFAULT '[]'::jsonb,
  dependent_task      TEXT DEFAULT '',
  aporte_snapshot     NUMERIC,
  finalized_at        TEXT
);

CREATE TABLE IF NOT EXISTS participants (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  is_super_user BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS indicators (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS app_config (
  key   TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE IF NOT EXISTS email_config (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  emails       TEXT[] DEFAULT '{}'::text[],
  frequency    TEXT DEFAULT 'weekly',
  send_day     TEXT DEFAULT 'monday',
  send_hour    INT DEFAULT 8,
  days_back    INT DEFAULT 7,
  days_forward INT DEFAULT 7,
  last_sent    TIMESTAMP WITH TIME ZONE
);

COMMIT;
