-- Migration 010: keep-alive table + email_config sequence fix + pg_cron backup.
--
-- Trae tres cosas:
--   1. Tabla `_keepalive` que el cron de Vercel + pg_cron actualizan cada 6
--      días con un caracter rotativo. Evita que Supabase Free pause el proyecto
--      tras 7 días sin actividad.
--   2. Re-sincroniza el sequence de email_config.id porque el upsert estaba
--      fallando con `duplicate key value violates unique constraint
--      "email_config_pkey"` cuando MAX(id) > nextval del sequence.
--   3. Programa un pg_cron como redundancia del keep-alive si el cron de
--      Vercel falla. Requiere la extensión pg_cron habilitada (Database >
--      Extensions). Si no está activada, la sección 3 hace skip silencioso.

BEGIN;

-- ── 1. Tabla de keep-alive ─────────────────────────────────
-- Una sola fila por diseño (CHECK id = 1). Sólo el service_role la toca
-- (RLS habilitada sin policies = nadie accede via PostgREST).
CREATE TABLE IF NOT EXISTS public._keepalive (
  id        INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  ch        CHAR(1) NOT NULL DEFAULT '.',
  pinged_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public._keepalive ENABLE ROW LEVEL SECURITY;

-- Sin policies: la tabla queda invisible para roles authenticated/anon. El
-- service_role bypassea RLS (lo usa api/cron.js) y pg_cron corre como
-- postgres (también bypassea).

INSERT INTO public._keepalive (id, ch) VALUES (1, '.')
ON CONFLICT (id) DO NOTHING;

-- ── 2. Reparar email_config.id ─────────────────────────────
-- Algunos entornos viejos quedaron con `id INTEGER DEFAULT 1` (sin sequence
-- ni IDENTITY) → cada INSERT sin id intenta usar 1 y choca contra el PK.
-- Esta migración:
--   a) Detecta si la columna no es IDENTITY ni tiene sequence.
--   b) Quita el DEFAULT literal y la convierte a IDENTITY.
--   c) Si ya es IDENTITY/SERIAL, sólo resincroniza el sequence (idempotente).
DO $$
DECLARE
  is_identity_col TEXT;
  cur_default     TEXT;
  next_id         BIGINT;
  seq_name        TEXT;
BEGIN
  SELECT is_identity, column_default
    INTO is_identity_col, cur_default
    FROM information_schema.columns
   WHERE table_schema = 'public'
     AND table_name   = 'email_config'
     AND column_name  = 'id';

  SELECT COALESCE(MAX(id), 0) + 1 INTO next_id FROM public.email_config;

  IF is_identity_col = 'YES' THEN
    EXECUTE format(
      'ALTER TABLE public.email_config ALTER COLUMN id RESTART WITH %s',
      next_id
    );
    RAISE NOTICE 'email_config.id ya era IDENTITY; reset a %', next_id;
  ELSE
    -- Quita el DEFAULT literal heredado y convierte a IDENTITY.
    seq_name := pg_get_serial_sequence('public.email_config', 'id');
    IF seq_name IS NOT NULL THEN
      -- Columna usa un sequence externo (SERIAL). Resync.
      PERFORM setval(seq_name, GREATEST(next_id - 1, 1), true);
      RAISE NOTICE 'email_config.id es SERIAL; sequence % set a %', seq_name, next_id - 1;
    ELSE
      -- No es IDENTITY ni SERIAL → la convertimos a IDENTITY.
      ALTER TABLE public.email_config ALTER COLUMN id DROP DEFAULT;
      EXECUTE format(
        'ALTER TABLE public.email_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
        next_id
      );
      RAISE NOTICE 'email_config.id convertido a IDENTITY desde %', next_id;
    END IF;
  END IF;
END $$;

-- Asegura idempotentemente que el UNIQUE constraint que la migración 006
-- intentó dejar siga existiendo (algunos entornos lo perdieron en migraciones
-- intermedias).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'email_config_project_id_key'
      AND conrelid = 'public.email_config'::regclass
  ) THEN
    ALTER TABLE public.email_config
      ADD CONSTRAINT email_config_project_id_key UNIQUE(project_id);
  END IF;
END $$;

COMMIT;

-- ── 3. pg_cron redundante (fuera de la transacción) ────────
-- Sólo corre si la extensión pg_cron está disponible. En Supabase Free hay
-- que habilitarla manualmente en: Database > Extensions > pg_cron.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    -- Desprograma el job anterior si existe (idempotente).
    PERFORM cron.unschedule(jobid)
    FROM cron.job
    WHERE jobname = 'w_planner_keepalive';

    -- Programa el job: cada 6 días al mediodía UTC.
    PERFORM cron.schedule(
      'w_planner_keepalive',
      '0 12 */6 * *',
      $cron$
        UPDATE public._keepalive
           SET ch = (ARRAY['.', ',', '*', '·', '~', ':'])[1 + floor(random()*6)::int],
               pinged_at = NOW()
         WHERE id = 1;
      $cron$
    );

    RAISE NOTICE 'pg_cron job w_planner_keepalive programado cada 6 días.';
  ELSE
    RAISE NOTICE 'pg_cron no está instalado. Skip. Habilítalo en Database > Extensions si quieres redundancia.';
  END IF;
END $$;

-- ── Verificación (corre manualmente después de aplicar) ────
-- SELECT * FROM public._keepalive;
--
-- SELECT column_name, is_identity, column_default
--   FROM information_schema.columns
--  WHERE table_schema='public' AND table_name='email_config' AND column_name='id';
-- -- expected: is_identity = 'YES'
--
-- INSERT INTO public.email_config (project_id, emails)
-- VALUES (-99, '["__seq_test__"]'::jsonb)
-- RETURNING id;
-- DELETE FROM public.email_config WHERE project_id = -99;
--
-- SELECT * FROM cron.job WHERE jobname = 'w_planner_keepalive';
