-- Migration 012: sistema de los 3 reportes.
--
-- Establece la fundación común:
--   1. report_configs — una fila por (proyecto, tipo). Reemplaza email_config
--      con destinatarios + schedule específicos por reporte (scrum, weekly_po,
--      monthly_team).
--   2. report_history — archivo plano de cada reporte enviado para que el
--      reporte mensual pueda comparar contra meses anteriores y detectar
--      patrones de comportamiento del equipo.
--   3. Backfill desde email_config hacia report_configs(weekly_po) para no
--      perder la configuración existente del reporte semanal.
--
-- RLS: solo owner del proyecto lee/escribe. Los reportes contienen datos
-- analíticos sensibles sobre miembros del equipo.

BEGIN;

-- ── 1. report_configs ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.report_configs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id  BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  report_type TEXT   NOT NULL CHECK (report_type IN ('scrum', 'weekly_po', 'monthly_team')),
  enabled     BOOLEAN NOT NULL DEFAULT true,
  recipients  TEXT[]  NOT NULL DEFAULT '{}',
  -- schedule guarda { days: ["monday",...], hour: 8, timezone: "America/Bogota" }
  schedule    JSONB   NOT NULL DEFAULT '{}'::jsonb,
  -- ventana de análisis: { days_back: 7, days_forward: 0 } por defecto.
  window_cfg  JSONB   NOT NULL DEFAULT '{}'::jsonb,
  last_sent   TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(project_id, report_type)
);

CREATE INDEX IF NOT EXISTS report_configs_project_idx ON public.report_configs(project_id);

ALTER TABLE public.report_configs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS report_configs_owner_all ON public.report_configs;
CREATE POLICY report_configs_owner_all ON public.report_configs
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = report_configs.project_id AND p.owner_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = report_configs.project_id AND p.owner_id = auth.uid()
    )
  );

-- ── 2. report_history (archivo plano) ──────────────────────
CREATE TABLE IF NOT EXISTS public.report_history (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id      BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  report_type     TEXT   NOT NULL CHECK (report_type IN ('scrum', 'weekly_po', 'monthly_team')),
  period_start    DATE   NOT NULL,
  period_end      DATE   NOT NULL,
  generated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- "sent" = enviado por correo, "stored" = solo guardado, "failed" = error,
  -- "truncated" = el modelo se quedó sin tokens.
  status          TEXT   NOT NULL DEFAULT 'sent' CHECK (status IN ('sent','stored','failed','truncated')),
  recipients      TEXT[] NOT NULL DEFAULT '{}',
  -- Texto plano del reporte (sin HTML), lo que sirve para comparar entre meses
  -- y para alimentar al modelo del reporte mensual.
  plain_text      TEXT   NOT NULL DEFAULT '',
  html            TEXT,
  model_used      TEXT,
  tokens_input    INTEGER,
  tokens_output   INTEGER,
  cost_usd        NUMERIC(10, 6),
  metadata        JSONB  NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS report_history_project_type_idx
  ON public.report_history(project_id, report_type, period_end DESC);

ALTER TABLE public.report_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS report_history_owner_select ON public.report_history;
CREATE POLICY report_history_owner_select ON public.report_history
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = report_history.project_id AND p.owner_id = auth.uid()
    )
  );

-- INSERT/UPDATE solo via service_role (los endpoints serverless), no via
-- cliente directo. No agregamos policies de INSERT para authenticated.

-- ── 3. Backfill desde email_config ─────────────────────────
-- El reporte semanal actual vive en email_config. Migramos cada fila a
-- report_configs(weekly_po) sin tocar email_config (lo dejamos como respaldo).
-- email_config.emails es JSONB (array de strings), lo convertimos a text[].
INSERT INTO public.report_configs (project_id, report_type, enabled, recipients, schedule, window_cfg, last_sent)
SELECT
  e.project_id,
  'weekly_po',
  COALESCE(jsonb_array_length(e.emails), 0) > 0,
  CASE
    WHEN e.emails IS NULL OR jsonb_typeof(e.emails) <> 'array' THEN '{}'::text[]
    ELSE ARRAY(SELECT jsonb_array_elements_text(e.emails))
  END,
  jsonb_build_object(
    'frequency', COALESCE(e.frequency, 'weekly'),
    'send_day',  COALESCE(e.send_day, 'monday'),
    'hour',      COALESCE(e.send_hour, 8),
    'timezone',  'America/Bogota'
  ),
  jsonb_build_object(
    'days_back',    COALESCE(e.days_back, 7),
    'days_forward', COALESCE(e.days_forward, 7)
  ),
  -- Algunos entornos tienen last_sent como TEXT. Casteamos de forma segura.
  NULLIF(e.last_sent::text, '')::timestamptz
FROM public.email_config e
WHERE e.project_id IS NOT NULL
ON CONFLICT (project_id, report_type) DO NOTHING;

-- ── 4. Trigger para updated_at ─────────────────────────────
CREATE OR REPLACE FUNCTION public.report_configs_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS report_configs_updated_at_trg ON public.report_configs;
CREATE TRIGGER report_configs_updated_at_trg
  BEFORE UPDATE ON public.report_configs
  FOR EACH ROW EXECUTE FUNCTION public.report_configs_set_updated_at();

COMMIT;

-- ── Verificación ───────────────────────────────────────────
-- SELECT project_id, report_type, recipients, schedule FROM public.report_configs;
-- SELECT count(*) FROM public.report_history;
