-- Migration 014: super-tareas (objetivos macro tipo "jarrón").
--
-- Una super-tarea es la "cabeza" de un grupo de tareas que la alimentan.
-- Se visualiza como un jarrón que se llena con el aporte acumulado de sus
-- tareas hijas en estado Finalizada, comparado con un target_aporte definido
-- al crear la super-tarea.
--
-- Una tarea puede pertenecer a varias super-tareas con pesos distintos —por
-- ejemplo, "Integración Temenos" puede aportar 70% a "Lanzar app v1" y 30%
-- a "Compliance bancario"— y por eso usamos una tabla pivote.
--
-- La vista por sprint se calcula on-the-fly desde el campo
-- tasks.custom_fields.sprint o tasks.sprint_id contra la tabla sprints,
-- sin necesidad de un nuevo cruce en BD.

BEGIN;

CREATE TABLE IF NOT EXISTS public.super_tasks (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id      BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  title           TEXT NOT NULL CHECK (length(title) > 0 AND length(title) <= 200),
  description     TEXT,
  -- Meta de aporte total que cuando se acumula con las tareas hijas
  -- completadas llena el jarrón al 100%.
  target_aporte   NUMERIC NOT NULL DEFAULT 100 CHECK (target_aporte > 0),
  -- Identidad visual: color y emoji que se mantienen en toda la app.
  color           TEXT NOT NULL DEFAULT '#542c9c',
  icon            TEXT NOT NULL DEFAULT '🎯',
  start_date      DATE,
  end_date        DATE,
  status          TEXT NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active', 'closed', 'paused')),
  position        INTEGER NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at      TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS super_tasks_project_idx
  ON public.super_tasks(project_id) WHERE deleted_at IS NULL;

-- Tabla pivote: una tarea puede alimentar varias super-tareas con peso.
-- weight 1.0 = aporte completo; 0.5 = mitad; etc.
CREATE TABLE IF NOT EXISTS public.task_super_links (
  task_id         BIGINT NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  super_task_id   BIGINT NOT NULL REFERENCES public.super_tasks(id) ON DELETE CASCADE,
  weight          NUMERIC NOT NULL DEFAULT 1.0 CHECK (weight > 0 AND weight <= 5),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (task_id, super_task_id)
);

CREATE INDEX IF NOT EXISTS task_super_links_super_idx
  ON public.task_super_links(super_task_id);

-- ── RLS ────────────────────────────────────────────────────
ALTER TABLE public.super_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_super_links ENABLE ROW LEVEL SECURITY;

-- super_tasks: miembros leen, owner edita
DROP POLICY IF EXISTS super_tasks_select ON public.super_tasks;
CREATE POLICY super_tasks_select ON public.super_tasks
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = super_tasks.project_id
        AND (p.owner_id = auth.uid()
             OR EXISTS (
               SELECT 1 FROM public.project_members m
               WHERE m.project_id = p.id AND m.user_id = auth.uid()
             ))
    )
  );

DROP POLICY IF EXISTS super_tasks_owner_all ON public.super_tasks;
CREATE POLICY super_tasks_owner_all ON public.super_tasks
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = super_tasks.project_id AND p.owner_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = super_tasks.project_id AND p.owner_id = auth.uid()
    )
  );

-- task_super_links: igual patrón
DROP POLICY IF EXISTS task_super_links_select ON public.task_super_links;
CREATE POLICY task_super_links_select ON public.task_super_links
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.super_tasks s
      JOIN public.projects p ON p.id = s.project_id
      WHERE s.id = task_super_links.super_task_id
        AND (p.owner_id = auth.uid()
             OR EXISTS (
               SELECT 1 FROM public.project_members m
               WHERE m.project_id = p.id AND m.user_id = auth.uid()
             ))
    )
  );

DROP POLICY IF EXISTS task_super_links_owner_all ON public.task_super_links;
CREATE POLICY task_super_links_owner_all ON public.task_super_links
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.super_tasks s
      JOIN public.projects p ON p.id = s.project_id
      WHERE s.id = task_super_links.super_task_id AND p.owner_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.super_tasks s
      JOIN public.projects p ON p.id = s.project_id
      WHERE s.id = task_super_links.super_task_id AND p.owner_id = auth.uid()
    )
  );

-- Trigger updated_at
CREATE OR REPLACE FUNCTION public.super_tasks_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS super_tasks_updated_at_trg ON public.super_tasks;
CREATE TRIGGER super_tasks_updated_at_trg
  BEFORE UPDATE ON public.super_tasks
  FOR EACH ROW EXECUTE FUNCTION public.super_tasks_set_updated_at();

COMMIT;

-- ── Verificación ───────────────────────────────────────────
-- SELECT * FROM public.super_tasks WHERE project_id = 27;
-- SELECT s.title, count(l.task_id) AS tareas_linkeadas
--   FROM public.super_tasks s
--   LEFT JOIN public.task_super_links l ON l.super_task_id = s.id
--   WHERE s.project_id = 27
--   GROUP BY s.id, s.title;
