-- Migration 019: chat en vivo del PO con la IA (feature Enterprise).
--
-- El PO conversa con un asistente que tiene cargado en su contexto:
--   - Las tarjetas profesionales del último evolutivo del proyecto
--   - Los últimos 2 reportes mensuales
--   - Estado actual de tareas + comentarios recientes
-- Y puede preguntar "¿quién está sobrecargado?", "arma una célula para
-- proyecto digital", "¿por qué Diego se atrasa?", sin esperar al reporte
-- bimensual.
--
-- Una sesión por proyecto (alcance acordado). Historial guardado para
-- continuar conversaciones.

BEGIN;

CREATE TABLE IF NOT EXISTS public.chat_sessions (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id    BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  owner_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  archived_at   TIMESTAMPTZ,
  metadata      JSONB NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE(project_id, owner_user_id, archived_at)
);

CREATE INDEX IF NOT EXISTS chat_sessions_project_idx
  ON public.chat_sessions(project_id, owner_user_id) WHERE archived_at IS NULL;

CREATE TABLE IF NOT EXISTS public.chat_messages (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id   BIGINT NOT NULL REFERENCES public.chat_sessions(id) ON DELETE CASCADE,
  role         TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content      TEXT NOT NULL,
  tokens_input INTEGER,
  tokens_output INTEGER,
  cost_usd     NUMERIC(10, 6),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS chat_messages_session_idx
  ON public.chat_messages(session_id, created_at);

ALTER TABLE public.chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

-- chat_sessions: solo el owner del proyecto (que también es owner del chat).
DROP POLICY IF EXISTS chat_sessions_owner_all ON public.chat_sessions;
CREATE POLICY chat_sessions_owner_all ON public.chat_sessions
  FOR ALL TO authenticated
  USING (owner_user_id = auth.uid())
  WITH CHECK (owner_user_id = auth.uid());

-- chat_messages: solo el dueño de la sesión asociada.
DROP POLICY IF EXISTS chat_messages_session_owner ON public.chat_messages;
CREATE POLICY chat_messages_session_owner ON public.chat_messages
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.chat_sessions s
      WHERE s.id = chat_messages.session_id AND s.owner_user_id = auth.uid()
    )
  );

-- INSERT/UPDATE solo via service_role (lo hace /api/chat-stream).

-- Trigger updated_at en sessions cuando se agrega un message.
CREATE OR REPLACE FUNCTION public.chat_session_touch()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  UPDATE public.chat_sessions SET updated_at = NOW() WHERE id = NEW.session_id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS chat_message_touch_session_trg ON public.chat_messages;
CREATE TRIGGER chat_message_touch_session_trg
  AFTER INSERT ON public.chat_messages
  FOR EACH ROW EXECUTE FUNCTION public.chat_session_touch();

COMMIT;
