-- Migration: Productivity-Plus improvements
-- Adds task type configuration, atomic task ID reservation, and app config defaults.

BEGIN;

CREATE TABLE IF NOT EXISTS task_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

INSERT INTO task_types (name) VALUES
  ('Administrativa'),
  ('Operativa'),
  ('Apadrinamiento'),
  ('Seguimiento'),
  ('Creativa'),
  ('Otra')
ON CONFLICT (name) DO NOTHING;

CREATE OR REPLACE FUNCTION claim_task_id()
RETURNS BIGINT AS $$
DECLARE
  current_value BIGINT;
BEGIN
  LOOP
    UPDATE app_config
    SET value = ((value::text::BIGINT + 1)::TEXT)
    WHERE key = 'nextId'
    RETURNING value::text::BIGINT INTO current_value;

    IF FOUND THEN
      RETURN current_value - 1;
    END IF;

    BEGIN
      INSERT INTO app_config ("key", value)
      VALUES ('nextId', '2');
      RETURN 1;
    EXCEPTION WHEN unique_violation THEN
      -- Another process wrote the row first, retry.
    END;
  END LOOP;
END;
$$ LANGUAGE plpgsql VOLATILE;

INSERT INTO app_config ("key", value)
VALUES
  ('nextId', '1'),
  ('weights', '{"tiempo":33,"dificultad":34,"estrategico":33}'),
  ('currentUserId', NULL)
ON CONFLICT ("key") DO NOTHING;

COMMIT;
