-- Migration 013: bitácora de avance por tarea (task_comments).
--
-- Hasta hoy cada tarea tiene un solo campo `comments` que el responsable
-- edita y sobrescribe. Eso pierde contexto histórico (qué se dijo hace 3
-- días, quién dijo qué) y los reportes solo ven el último estado del texto.
--
-- task_comments es un thread cronológico por tarea: cualquier miembro del
-- proyecto puede dejar un comentario de avance ("hoy logré X", "esperando
-- a Y", "encontré que Z"). El autor queda guardado, los demás miembros lo
-- ven, y los reportes ahora pueden razonar sobre la conversación y no solo
-- sobre el último estado del texto.
--
-- El campo `tasks.comments` se mantiene como "descripción / observación
-- general" — convive con el thread sin migrarlo.

BEGIN;

CREATE TABLE IF NOT EXISTS public.task_comments (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id         BIGINT NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  project_id      BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  -- Autor: idealmente un user_id real, pero también soportamos nombres
  -- "huérfanos" para participantes que aún no se autenticaron (heredan del
  -- nombre que el usuario tipea).
  author_user_id  UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  author_name     TEXT NOT NULL,
  text            TEXT NOT NULL CHECK (length(text) > 0 AND length(text) <= 4000),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- Soft delete para mantener orden cronológico y permitir referencia
  -- desde los reportes (el autor puede borrar; el texto se vacía o se
  -- marca, no se pierde la columna).
  deleted_at      TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS task_comments_task_idx
  ON public.task_comments(task_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS task_comments_project_idx
  ON public.task_comments(project_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS task_comments_author_idx
  ON public.task_comments(author_user_id) WHERE deleted_at IS NULL;

ALTER TABLE public.task_comments ENABLE ROW LEVEL SECURITY;

-- ── Helper: ¿es miembro del proyecto? Reusa el helper de migración 006.
-- Si no existe, los reportes igual funcionan via service_role.

-- SELECT: todos los miembros del proyecto leen el thread
DROP POLICY IF EXISTS task_comments_select ON public.task_comments;
CREATE POLICY task_comments_select ON public.task_comments
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = task_comments.project_id
        AND (p.owner_id = auth.uid()
             OR EXISTS (
               SELECT 1 FROM public.project_members m
               WHERE m.project_id = p.id AND m.user_id = auth.uid()
             ))
    )
  );

-- INSERT: cualquier miembro del proyecto, autor = ellos mismos
DROP POLICY IF EXISTS task_comments_insert ON public.task_comments;
CREATE POLICY task_comments_insert ON public.task_comments
  FOR INSERT TO authenticated
  WITH CHECK (
    author_user_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = task_comments.project_id
        AND (p.owner_id = auth.uid()
             OR EXISTS (
               SELECT 1 FROM public.project_members m
               WHERE m.project_id = p.id AND m.user_id = auth.uid()
             ))
    )
  );

-- UPDATE: solo el autor edita su propio comentario
DROP POLICY IF EXISTS task_comments_update_own ON public.task_comments;
CREATE POLICY task_comments_update_own ON public.task_comments
  FOR UPDATE TO authenticated
  USING (author_user_id = auth.uid())
  WITH CHECK (author_user_id = auth.uid());

-- DELETE: el autor o el owner del proyecto
DROP POLICY IF EXISTS task_comments_delete ON public.task_comments;
CREATE POLICY task_comments_delete ON public.task_comments
  FOR DELETE TO authenticated
  USING (
    author_user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = task_comments.project_id AND p.owner_id = auth.uid()
    )
  );

-- Trigger para updated_at automático
CREATE OR REPLACE FUNCTION public.task_comments_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.text <> OLD.text THEN
    NEW.updated_at = NOW();
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS task_comments_updated_at_trg ON public.task_comments;
CREATE TRIGGER task_comments_updated_at_trg
  BEFORE UPDATE ON public.task_comments
  FOR EACH ROW EXECUTE FUNCTION public.task_comments_set_updated_at();

COMMIT;

-- ── Verificación ───────────────────────────────────────────
-- SELECT count(*) FROM public.task_comments;
-- SELECT * FROM public.task_comments WHERE task_id = <id> ORDER BY created_at;
