-- Migration 018: tarjetas profesionales bimensuales (evolutivo Pro Power+).
--
-- Cada 2 meses, para cada usuario activo en un proyecto Pro Power, la IA
-- genera una "tarjeta profesional" que describe rol detectado, fortalezas,
-- oportunidades, proyectos donde brilla y donde sufre. Las tarjetas se
-- guardan en histórico para que reportes futuros puedan comparar evolución.
--
-- Reglas:
--   - Solo se genera tarjeta para participantes con >=60 días de actividad
--     (creación de tareas, comentarios, cierres). Antes muestra "Construyendo
--     perfil" en la UI.
--   - El conjunto de tarjetas + recomendaciones de células se persisten
--     como una sola fila por (project_id, period_start, period_end).
--   - Solo el owner del proyecto las lee.

BEGIN;

CREATE TABLE IF NOT EXISTS public.user_evolutions (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id        BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  period_start      DATE NOT NULL,
  period_end        DATE NOT NULL,
  generated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status            TEXT NOT NULL DEFAULT 'stored'
                      CHECK (status IN ('stored', 'failed', 'truncated')),
  -- cards: array de tarjetas por persona
  --   [{ person, days_active, confidence, role_detected,
  --      strengths: [{text, evidence: [task_id, ...]}],
  --      improvements: [{text, evidence: [...]}],
  --      shines_in, struggles_in, signals: [...] }]
  cards             JSONB NOT NULL DEFAULT '[]'::jsonb,
  -- recomendaciones: array de células sugeridas
  --   [{ project_type, members: [name1, name2], rationale }]
  cell_suggestions  JSONB NOT NULL DEFAULT '[]'::jsonb,
  -- Texto plano usado para alimentar al próximo bimestral (similar a report_history)
  plain_text        TEXT NOT NULL DEFAULT '',
  -- HTML opcional para correo si quieres enviarlo al owner
  html              TEXT,
  model_used        TEXT,
  tokens_input      INTEGER,
  tokens_output     INTEGER,
  cost_usd          NUMERIC(10, 6),
  metadata          JSONB NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE(project_id, period_start, period_end)
);

CREATE INDEX IF NOT EXISTS user_evolutions_project_idx
  ON public.user_evolutions(project_id, period_end DESC);

ALTER TABLE public.user_evolutions ENABLE ROW LEVEL SECURITY;

-- Solo el owner del proyecto puede leer las tarjetas (privacy alta).
DROP POLICY IF EXISTS user_evolutions_owner_select ON public.user_evolutions;
CREATE POLICY user_evolutions_owner_select ON public.user_evolutions
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = user_evolutions.project_id AND p.owner_id = auth.uid()
    )
  );

-- INSERT/UPDATE/DELETE solo via service_role (los endpoints). Sin política
-- para authenticated.

-- Helper: días de actividad de un participante en un proyecto.
-- Cuenta días distintos donde la persona apareció como responsable de tarea
-- creada, actualizada o cerrada, o como autor de comentario (si existe).
CREATE OR REPLACE FUNCTION public.participant_days_active(p_project_id BIGINT, p_name TEXT)
RETURNS INTEGER
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  WITH activity AS (
    SELECT DISTINCT date_trunc('day', d) AS dia FROM (
      SELECT inserted_at AS d FROM public.tasks
        WHERE project_id = p_project_id AND responsible = p_name AND inserted_at IS NOT NULL
      UNION ALL
      SELECT updated_at  AS d FROM public.tasks
        WHERE project_id = p_project_id AND responsible = p_name AND updated_at  IS NOT NULL
      UNION ALL
      SELECT closed_at   AS d FROM public.tasks
        WHERE project_id = p_project_id AND responsible = p_name AND closed_at   IS NOT NULL
      UNION ALL
      -- Comentarios del thread (migración 013); tolera si no existe.
      SELECT c.created_at AS d FROM public.task_comments c
        WHERE c.project_id = p_project_id AND c.author_name = p_name AND c.deleted_at IS NULL
    ) all_events
    WHERE d IS NOT NULL
  )
  SELECT COUNT(*)::int FROM activity;
$$;

GRANT EXECUTE ON FUNCTION public.participant_days_active(BIGINT, TEXT) TO authenticated;

COMMIT;

-- ── Verificación ───────────────────────────────────────────
-- SELECT participant_days_active(27, 'Diego Rojas');
-- SELECT public.project_can_use_evolutivo(27);
