-- Migration 020: retrospectiva al cierre de sprint + Pulso del equipo.
--
-- Cada vez que un sprint cierra (status='closed' o 3 días después de
-- end_date), se abre un período de retrospectiva. Los participantes del
-- sprint deben responder con:
--   - Emoji de emoción al cierre del sprint
--   - Lo que les gustó (1 párrafo max)
--   - Lo que no les gustó (1 párrafo max)
--   - 3 señalizaciones de pares (anónimas en la vista, agregadas):
--       a) quien aportó más estratégicamente
--       b) quien podría dar más
--       c) quien la pasó difícil
--
-- Las respuestas alimentan al Evolutivo como input cualitativo y se
-- consolidan en una vista "Pulso del equipo" visible solo al owner.
--
-- Bloqueo blando: respuesta obligatoria con notificación al owner si no
-- se completa en el plazo. Sin bloqueo de otras features.
--
-- Gating: feature 'team_pulse' disponible desde Pro Solo en adelante.

BEGIN;

-- ── 0. Agregar feature team_pulse a los tiers Pro+ ─────────
UPDATE public.tier_limits
   SET features = array_append(features, 'team_pulse')
 WHERE tier IN ('pro_solo','pro_team','pro_power','enterprise')
   AND NOT ('team_pulse' = ANY(features));

-- ── 1. sprint_retro_periods ────────────────────────────────
-- Período abierto para responder retrospectiva de un sprint específico.
CREATE TABLE IF NOT EXISTS public.sprint_retro_periods (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sprint_id   BIGINT NOT NULL REFERENCES public.sprints(id) ON DELETE CASCADE,
  project_id  BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  opened_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  closes_at   TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '7 days'),
  status      TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed')),
  -- 'sprint_closed' = abierto cuando el owner marco el sprint como closed.
  -- 'end_date_passed' = abierto automaticamente N dias despues del end_date.
  trigger     TEXT NOT NULL DEFAULT 'sprint_closed' CHECK (trigger IN ('sprint_closed','end_date_passed','manual')),
  notifications_sent BOOLEAN NOT NULL DEFAULT false,
  reminder_sent_at TIMESTAMPTZ,
  metadata    JSONB NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE(sprint_id)
);

CREATE INDEX IF NOT EXISTS sprint_retro_periods_project_idx
  ON public.sprint_retro_periods(project_id, status);

-- ── 2. sprint_retros (respuesta individual) ────────────────
CREATE TABLE IF NOT EXISTS public.sprint_retros (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_id         BIGINT NOT NULL REFERENCES public.sprint_retro_periods(id) ON DELETE CASCADE,
  respondent_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  respondent_name   TEXT NOT NULL,
  -- Emoji de emoción al cierre. Set acotado para que la IA pueda
  -- interpretar consistentemente.
  emoji             TEXT NOT NULL CHECK (emoji IN ('😄','😐','😟','😡','🥱','🔥','💪','😴','😍','😅','🤝','🌟')),
  liked             TEXT NOT NULL CHECK (length(liked) > 0 AND length(liked) <= 2000),
  disliked          TEXT NOT NULL CHECK (length(disliked) > 0 AND length(disliked) <= 2000),
  submitted_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(period_id, respondent_user_id)
);

CREATE INDEX IF NOT EXISTS sprint_retros_period_idx
  ON public.sprint_retros(period_id);

-- ── 3. sprint_retro_peer_signals (señalizaciones por pares) ─
-- Cada respondiente puede señalar 1 nombre por tipo de señal. Anónimas en
-- la vista: el owner ve solo conteos agregados por nombre. Pero la IA del
-- Evolutivo puede acceder al detalle vía service_role para entender quien
-- vota a quien (usado solo para análisis, no se expone al usuario).
CREATE TABLE IF NOT EXISTS public.sprint_retro_peer_signals (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  retro_id       BIGINT NOT NULL REFERENCES public.sprint_retros(id) ON DELETE CASCADE,
  -- 'strategic_contributor' = quien aporto mas estrategicamente al equipo
  -- 'could_give_more'       = quien podria dar mas
  -- 'had_it_tough'          = quien la paso dificil sin ser por falta de ganas
  signal_type    TEXT NOT NULL CHECK (signal_type IN ('strategic_contributor','could_give_more','had_it_tough')),
  signaled_name  TEXT NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(retro_id, signal_type)
);

CREATE INDEX IF NOT EXISTS sprint_retro_peer_signals_retro_idx
  ON public.sprint_retro_peer_signals(retro_id);

-- ── RLS ────────────────────────────────────────────────────
ALTER TABLE public.sprint_retro_periods   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sprint_retros          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sprint_retro_peer_signals ENABLE ROW LEVEL SECURITY;

-- sprint_retro_periods: miembros del proyecto leen (para mostrar banner).
DROP POLICY IF EXISTS sprint_retro_periods_member_select ON public.sprint_retro_periods;
CREATE POLICY sprint_retro_periods_member_select ON public.sprint_retro_periods
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.projects p
      WHERE p.id = sprint_retro_periods.project_id
        AND (p.owner_id = auth.uid()
             OR EXISTS (SELECT 1 FROM public.project_members m
                        WHERE m.project_id = p.id AND m.user_id = auth.uid()))
    )
  );

-- sprint_retros: miembros pueden insertar su propia respuesta (1 por sprint).
-- Pueden leer su propia respuesta para editar. Owner ve todas.
DROP POLICY IF EXISTS sprint_retros_own_or_owner ON public.sprint_retros;
CREATE POLICY sprint_retros_own_or_owner ON public.sprint_retros
  FOR SELECT TO authenticated
  USING (
    respondent_user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.sprint_retro_periods p
      JOIN public.projects pr ON pr.id = p.project_id
      WHERE p.id = sprint_retros.period_id AND pr.owner_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS sprint_retros_member_insert ON public.sprint_retros;
CREATE POLICY sprint_retros_member_insert ON public.sprint_retros
  FOR INSERT TO authenticated
  WITH CHECK (
    respondent_user_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.sprint_retro_periods p
      JOIN public.projects pr ON pr.id = p.project_id
      WHERE p.id = sprint_retros.period_id
        AND p.status = 'open'
        AND (pr.owner_id = auth.uid()
             OR EXISTS (SELECT 1 FROM public.project_members m
                        WHERE m.project_id = pr.id AND m.user_id = auth.uid()))
    )
  );

DROP POLICY IF EXISTS sprint_retros_own_update ON public.sprint_retros;
CREATE POLICY sprint_retros_own_update ON public.sprint_retros
  FOR UPDATE TO authenticated
  USING (respondent_user_id = auth.uid())
  WITH CHECK (respondent_user_id = auth.uid());

-- peer_signals: cada quien inserta/edita las suyas. Owner ve solo via
-- service_role o RPC agregada (para anonimato en la UI).
DROP POLICY IF EXISTS sprint_retro_peer_signals_own ON public.sprint_retro_peer_signals;
CREATE POLICY sprint_retro_peer_signals_own ON public.sprint_retro_peer_signals
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.sprint_retros r
      WHERE r.id = sprint_retro_peer_signals.retro_id AND r.respondent_user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.sprint_retros r
      WHERE r.id = sprint_retro_peer_signals.retro_id AND r.respondent_user_id = auth.uid()
    )
  );

-- ── Trigger updated_at en sprint_retros ────────────────────
CREATE OR REPLACE FUNCTION public.sprint_retros_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;

DROP TRIGGER IF EXISTS sprint_retros_updated_at_trg ON public.sprint_retros;
CREATE TRIGGER sprint_retros_updated_at_trg
  BEFORE UPDATE ON public.sprint_retros
  FOR EACH ROW EXECUTE FUNCTION public.sprint_retros_set_updated_at();

-- ── RPC: vista agregada para el owner (Pulso del equipo) ───
-- Devuelve por cada sprint con retro abierta/cerrada en el proyecto:
--   - sprint info
--   - sentimiento general (conteo de emojis)
--   - tasa de respuesta
--   - "guerreros" (conteo por nombre de señal strategic_contributor)
--   - "oportunidades" (conteo de could_give_more)
--   - "duros" (conteo de had_it_tough)
--   - los párrafos liked/disliked agregados como texto plano (para que el
--     evolutivo los lea como evidencia)
CREATE OR REPLACE FUNCTION public.team_pulse_for_project(p_project_id BIGINT)
RETURNS TABLE(
  sprint_id    BIGINT,
  sprint_name  TEXT,
  start_date   DATE,
  end_date     DATE,
  period_id    BIGINT,
  period_status TEXT,
  total_respondents INTEGER,
  emoji_breakdown JSONB,
  strategic_warriors JSONB,
  could_give_more JSONB,
  had_it_tough JSONB,
  liked_aggregate TEXT,
  disliked_aggregate TEXT
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  WITH agg AS (
    SELECT
      p.sprint_id,
      s.name AS sprint_name,
      s.start_date, s.end_date,
      p.id AS period_id,
      p.status::text AS period_status,
      COUNT(DISTINCT r.id)::int AS total_respondents,
      (
        SELECT jsonb_object_agg(emoji, c) FROM (
          SELECT r2.emoji, COUNT(*) AS c FROM public.sprint_retros r2
          WHERE r2.period_id = p.id GROUP BY r2.emoji
        ) e
      ) AS emoji_breakdown,
      (
        SELECT COALESCE(jsonb_object_agg(name, c), '{}'::jsonb) FROM (
          SELECT signaled_name AS name, COUNT(*) AS c
          FROM public.sprint_retro_peer_signals s
          JOIN public.sprint_retros r2 ON r2.id = s.retro_id
          WHERE r2.period_id = p.id AND s.signal_type = 'strategic_contributor'
          GROUP BY signaled_name ORDER BY COUNT(*) DESC
        ) x
      ) AS strategic_warriors,
      (
        SELECT COALESCE(jsonb_object_agg(name, c), '{}'::jsonb) FROM (
          SELECT signaled_name AS name, COUNT(*) AS c
          FROM public.sprint_retro_peer_signals s
          JOIN public.sprint_retros r2 ON r2.id = s.retro_id
          WHERE r2.period_id = p.id AND s.signal_type = 'could_give_more'
          GROUP BY signaled_name ORDER BY COUNT(*) DESC
        ) x
      ) AS could_give_more,
      (
        SELECT COALESCE(jsonb_object_agg(name, c), '{}'::jsonb) FROM (
          SELECT signaled_name AS name, COUNT(*) AS c
          FROM public.sprint_retro_peer_signals s
          JOIN public.sprint_retros r2 ON r2.id = s.retro_id
          WHERE r2.period_id = p.id AND s.signal_type = 'had_it_tough'
          GROUP BY signaled_name ORDER BY COUNT(*) DESC
        ) x
      ) AS had_it_tough,
      string_agg(r.liked, E'\n\n') AS liked_aggregate,
      string_agg(r.disliked, E'\n\n') AS disliked_aggregate
    FROM public.sprint_retro_periods p
    JOIN public.sprints s ON s.id = p.sprint_id
    LEFT JOIN public.sprint_retros r ON r.period_id = p.id
    WHERE p.project_id = p_project_id
      AND EXISTS (
        SELECT 1 FROM public.projects pr
        WHERE pr.id = p_project_id AND pr.owner_id = auth.uid()
      )
    GROUP BY p.sprint_id, s.name, s.start_date, s.end_date, p.id, p.status
    ORDER BY s.start_date DESC
  )
  SELECT * FROM agg;
$$;

GRANT EXECUTE ON FUNCTION public.team_pulse_for_project(BIGINT) TO authenticated;

-- ── RPC: quien no respondio? (para bloqueo blando + cron) ──
CREATE OR REPLACE FUNCTION public.sprint_retro_pending_for_user(p_user_id UUID DEFAULT auth.uid())
RETURNS TABLE(
  period_id   BIGINT,
  sprint_id   BIGINT,
  sprint_name TEXT,
  project_id  BIGINT,
  project_name TEXT,
  closes_at   TIMESTAMPTZ
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT
    p.id, p.sprint_id, s.name, p.project_id, pr.name, p.closes_at
  FROM public.sprint_retro_periods p
  JOIN public.sprints s ON s.id = p.sprint_id
  JOIN public.projects pr ON pr.id = p.project_id
  WHERE p.status = 'open'
    AND p.closes_at > NOW()
    -- El usuario es miembro o owner del proyecto
    AND (
      pr.owner_id = p_user_id
      OR EXISTS (
        SELECT 1 FROM public.project_members m
        WHERE m.project_id = pr.id AND m.user_id = p_user_id
      )
    )
    -- Y no ha respondido aun
    AND NOT EXISTS (
      SELECT 1 FROM public.sprint_retros r
      WHERE r.period_id = p.id AND r.respondent_user_id = p_user_id
    )
  ORDER BY p.closes_at ASC;
$$;

GRANT EXECUTE ON FUNCTION public.sprint_retro_pending_for_user(UUID) TO authenticated;

COMMIT;

-- ── Verificación ───────────────────────────────────────────
-- SELECT features FROM public.tier_limits WHERE tier='pro_solo'; -- debe incluir 'team_pulse'
-- SELECT * FROM public.team_pulse_for_project(27);
-- SELECT * FROM public.sprint_retro_pending_for_user();
