-- ─────────────────────────────────────────────────────────────────────────────
-- FIX CRÍTICO — Las invitaciones nunca funcionaron: "Código inválido o proyecto
-- no encontrado" para TODO invitado nuevo.
--
-- SÍNTOMA
--   El dueño envía la invitación (api/invite.js), el invitado abre el enlace
--   /app?join=<code> o pega el código, y la app responde
--   "Código inválido o proyecto no encontrado."
--
-- CAUSA RAÍZ
--   public.participants.id es `bigint NOT NULL` SIN DEFAULT y SIN IDENTITY
--   (nunca existió participants_id_seq). El RPC join_project_by_invite_code()
--   hace:
--       INSERT INTO participants(name, is_super_user, project_id, auth_user_id, email)
--       SELECT ... WHERE NOT EXISTS (...)
--   es decir, SIN id. Ese INSERT falla con
--       23502  null value in column "id" of relation "participants"
--   y como el RPC es una sola transacción, aborta la función completa —
--   incluido el INSERT previo en project_members. PostgREST devuelve error, el
--   cliente cae al fallback `select * from projects where invite_code = …` que
--   RLS (projects_select_member) bloquea porque el invitado todavía NO es
--   miembro, y el resultado null se muestra como "código inválido".
--
--   Evidencia previa a este fix, en producción:
--     · 0 filas en participants con auth_user_id IS NOT NULL (el RPC nunca pudo
--       insertar ninguna).
--     · todos los proyectos con exactamente 1 fila en project_members (el dueño).
--
--   public.indicators.id arrastra el mismo defecto: los indicadores de las
--   plantillas (ProjectLandingScreen.createFromTemplate) se insertan sin id y
--   fallan en silencio.
--
-- SOLUCIÓN
--   Convertir ambas columnas en IDENTITY **BY DEFAULT** (no ALWAYS):
--     · BY DEFAULT sigue aceptando los ids que el cliente genera hoy
--       (useProjectConfig.saveParticipants/saveIndicators usan Date.now()), así
--       que no rompe ningún camino existente.
--     · Y auto-genera el id cuando el INSERT lo omite, que es lo que hacen el
--       RPC de invitación y useProjectData.
--     · Las columnas IDENTITY no necesitan GRANT USAGE sobre la secuencia para
--       el rol `authenticated` (a diferencia de serial/nextval), así que no hay
--       que tocar permisos.
--   La secuencia arranca por encima del máximo actual para no colisionar con
--   los ids históricos generados por el cliente.
--
--   Además: índice único parcial en participants(project_id, auth_user_id) para
--   que el "insert-if-not-exists" del RPC sea idempotente también bajo carrera
--   (dos pestañas aceptando la misma invitación a la vez no duplican la ficha).
--
-- IDEMPOTENTE: se puede correr varias veces sin efecto.
-- ─────────────────────────────────────────────────────────────────────────────

BEGIN;

DO $$
DECLARE
  v_seq  TEXT;
  v_max  BIGINT;
  v_tbl  TEXT;
BEGIN
  FOREACH v_tbl IN ARRAY ARRAY['participants', 'indicators'] LOOP
    -- Solo intervenimos si la columna sigue sin forma de generar su id.
    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name   = v_tbl
        AND column_name  = 'id'
        AND (is_identity = 'YES' OR column_default IS NOT NULL)
    ) THEN
      EXECUTE format(
        'ALTER TABLE public.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY',
        v_tbl
      );
      RAISE NOTICE '%.id -> GENERATED BY DEFAULT AS IDENTITY', v_tbl;
    ELSE
      RAISE NOTICE '%.id ya generaba su valor; sin cambios', v_tbl;
    END IF;

    -- Reposiciona la secuencia por encima del máximo histórico. Se ejecuta
    -- siempre (no solo al crear la identity) para que reaplicar la migración
    -- corrija una secuencia que haya quedado atrasada.
    v_seq := pg_get_serial_sequence('public.' || v_tbl, 'id');
    IF v_seq IS NOT NULL THEN
      EXECUTE format('SELECT COALESCE(MAX(id), 0) FROM public.%I', v_tbl) INTO v_max;
      PERFORM setval(v_seq, GREATEST(v_max, 1), true);
      RAISE NOTICE '  secuencia % posicionada en %', v_seq, GREATEST(v_max, 1);
    END IF;
  END LOOP;
END $$;

-- Un usuario autenticado no puede tener dos fichas de participante en el mismo
-- tablero. Parcial: las fichas manuales (sin auth_user_id) no quedan afectadas.
CREATE UNIQUE INDEX IF NOT EXISTS participants_project_auth_user_uniq
  ON public.participants (project_id, auth_user_id)
  WHERE auth_user_id IS NOT NULL;

COMMIT;

-- ─── Verificación (correr después de aplicar) ────────────────────────────────
--
-- 1) Ambas columnas deben reportar is_identity = YES y una secuencia asociada:
--
-- SELECT table_name, column_name, is_identity, column_default,
--        pg_get_serial_sequence('public.'||table_name, column_name) AS seq
-- FROM information_schema.columns
-- WHERE table_schema='public' AND table_name IN ('participants','indicators')
--   AND column_name='id';
--
-- 2) Prueba de humo del flujo completo de invitación, sin efectos secundarios
--    (ver scripts/smoke-join-invite.sql). Debe devolver el proyecto:
--
-- BEGIN;
--   SELECT set_config('diag.code', (SELECT invite_code FROM public.projects WHERE id = <ID>), true);
--   SELECT set_config('request.jwt.claims',
--     '{"sub":"00000000-0000-4000-8000-0000000d1a91","email":"smoke@example.com","role":"authenticated"}', true);
--   SET LOCAL ROLE authenticated;
--   SELECT id, name FROM public.join_project_by_invite_code(current_setting('diag.code'));
-- ROLLBACK;
